### ISSUE TITLE
minor bug on the extension on iphone

### ISSUE THREAD

**Issue by rie39414** [nienow/sn-quill#17]
the extension, opened on iPhone, shows the background color of the note as white, even if the dark theme of the app is selected

![IMG_7681](https://github.com/nienow/sn-quill/assets/145783398/1fe80881-10f5-4522-8a1a-0b2faac3ce65)

**Comment by nienow** [comment]
I put in a quick fix, and it works for Android. @rie39414 Let me know if iPhone is working as well. Thanks.

**Comment by rie39414** [comment]
it worked perfectly on iPhone, thank you very much!
